### ISSUE TITLE
GET https://use.fontawesome.com/releases/v5.6.3/css/fontawesome.css net::ERR_TIMED_OUT

### ISSUE THREAD

**Issue by VVlhw** [fzankl/docsify-plugin-flexible-alerts#15]
![image](https://user-images.githubusercontent.com/55015260/89800871-ee077c00-db61-11ea-902b-83ba6ed5dfa9.png)
![image](https://user-images.githubusercontent.com/55015260/89799880-9e748080-db60-11ea-8ea9-4a8d57d22c6c.png)

First of all, I really like this plugin，but i have something wrong.
my docsify loading slowly, the console message is 【fontawesome】fail to load

i had try to download fontawesome, and import relevant document in `index.html`
after doing this, fontawesome can work, but docsify still loading slowly due to the fail request

Is there a way to solve it,  i really really love this plugin~~

**Comment by VVlhw** [comment]
someone told me this following solution:
1、download `https://unpkg.com/docsify-plugin-flexible-alerts@1.0.4/dist/docsify-plugin-flexible-alerts.min.js`
2、delete fontawesome relevant import url 
3、import this modified file in docsify `index.html`
ps：download fontawesome, and import relevant document in `index.html`

**Comment by lerit** [comment]
same problem
