### ISSUE TITLE
Supporting Dark Mode for callout style

### ISSUE THREAD

**Issue by tied** [fzankl/docsify-plugin-flexible-alerts#17]
I really like the boxes :) But in dark mode they stay white.

- https://docsify-darklight-theme.boopathikumar.me (I use this)
- https://github.com/Plugin-contrib/docsify-plugin/tree/master/packages/docsify-dark-mode

Regards,
Tim

**Comment by fzankl** [comment]
@tied: Is this what you expect in dark mode?

![image](https://user-images.githubusercontent.com/44210522/93624657-f95f8a00-f9e0-11ea-9cb1-39afca30aac9.png)

**Comment by tied** [comment]
@fzankl exactly!

**Comment by fzankl** [comment]
Fixed in Release 1.1.0 of this plugin.
