### ISSUE TITLE
unpkg.com CDN broken

### ISSUE THREAD

**Issue by 6uhrmittag** [fzankl/docsify-plugin-flexible-alerts#20]
Looks like using unpgk.com as CDN is broken:

## Steps to reproduce
Include _unpkg.com_ CDN snippet in the index.html:

````JavaScript
<script src="https://unpkg.com/docsify-plugin-flexible-alerts"></script>
````

## Expected behaviour
No 404 in console.

Using _jsdelivr.com_ works without errors:

````JavaScript
<script src="https://cdn.jsdelivr.net/npm/docsify-plugin-flexible-alerts@latest/dist/docsify-plugin-flexible-alerts.min.js"></script>
````

## Actual behaviour
_unpkg.com_ produced this error in the Google Chrome Console:
> DevTools failed to load SourceMap: Could not load content for https://unpkg.com/docsify-plugin-flexible-alerts.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

## Possible fixes

I'm not familiar with how unpkg.com works - what I've noticed is, that `https://unpkg.com/docsify-plugin-flexible-alerts` would work:

````cmd
curl -I https://unpkg.com/docsify-plugin-flexible-alerts.min.js.map
HTTP/2 404
date: Tue, 09 Feb 2021 06:00:03 GMT
````

````cmd
curl -I https://unpkg.com/docsify-plugin-flexible-alerts
HTTP/2 302
date: Tue, 09 Feb 2021 05:59:41 GMT
````

**Comment by fzankl** [comment]
When using unpkg.com it is not possible to reference files directly without specifying a package version.

The following URLs should work as expected:
 - https://unpkg.com/docsify-plugin-flexible-alerts
 - https://unpkg.com/docsify-plugin-flexible-alerts@latest
 - https://unpkg.com/docsify-plugin-flexible-alerts@latest/dist/docsify-plugin-flexible-alerts.min.js
 - https://unpkg.com/docsify-plugin-flexible-alerts@1.1.0/dist/docsify-plugin-flexible-alerts.min.js
