### ISSUE TITLE
Unable to display

### ISSUE THREAD

**Issue by yyhhkya** [fzankl/docsify-plugin-flexible-alerts#30]
The two "alerts" together will result in the above cannot be displayed

### index.html

![image](https://user-images.githubusercontent.com/87574541/197658902-320ed0e1-103b-4e4b-9689-b31df4fe1fe4.png)

![image](https://user-images.githubusercontent.com/87574541/197658961-d25e1e07-9c18-4f8a-bbe7-9ceb77620529.png)

### bans.md

![image](https://user-images.githubusercontent.com/87574541/197659104-912c11b3-b213-43cf-8572-625ba0ca082b.png)

### Webpage

![image](https://user-images.githubusercontent.com/87574541/197659199-848afaa3-48ae-4746-9263-15101cc86b55.png)

### problem

"Tip" cannot be displayed

**Comment by fzankl** [comment]
Can you possibly provide the example as code?
This would make it easier to reproduce the problem.

**Comment by yyhhkya** [comment]
OK, because I'm going to bed. I'll send it to you at utc6:00.

**Comment by yyhhkya** [comment]
The above "ban. md" picture

**Comment by yyhhkya** [comment]
![image](https://user-images.githubusercontent.com/87574541/198610609-6e3c27a1-678e-4d65-9a4f-0c72e8f53324.png)
This is what happens when the browser cache is cleared

**Comment by yixiu025** [comment]
I have the same problem.
It does not have the same problem in version 1.0.4 .
Please help, Thanks.

**Comment by fzankl** [comment]
> The above "ban. md" picture

Sorry, but I cannot find any code snippet.
To be able to reproduce the issue, I need the content of the files `index.html` and `ban.md`

**Comment by yyhhkya** [comment]
Do I need to provide "index. html" file and "ban. md" file

**Comment by yyhhkya** [comment]
[Desktop.zip](https://github.com/fzankl/docsify-plugin-flexible-alerts/files/10082258/Desktop.zip)

**Comment by yixiu025** [comment]
this can solve, after every `alert` append a `space symbol`, e.g.
如下方案可解决此问题, 在每一个`alert`末尾增加一个`空格`
```
> [!NOTE]
> 提示信息2 

> [!TIP]
> 提示信息2 
```

**Comment by qyh214** [comment]
confirm,can in first alert end add `space` can temporary fix.

**Comment by fzankl** [comment]
@yyhhkya @qyh214 @yixiu025 
Can you please confirm that the associated PR does fix the issue?

**Comment by qyh214** [comment]
@fzankl It seems that test needs to be self compiled, because I directly request `https://unpkg.com/docsify-plugin-flexible-alerts`,maybe can you give me compiled version and I can test it quickly

**Comment by fzankl** [comment]
@qyh214 
I've uploaded a compiled and minified version to a separate branch.
Just use this URL to use the version including the fix:
https://raw.githubusercontent.com/fzankl/docsify-plugin-flexible-alerts/30-unable-to-display-compiled/docsify-plugin-flexible-alerts.min.js

**Comment by qyh214** [comment]
> @qyh214 I've uploaded a compiled and minified version to a separate branch. Just use this URL to use the version including the fix: https://raw.githubusercontent.com/fzankl/docsify-plugin-flexible-alerts/30-unable-to-display-compiled/docsify-plugin-flexible-alerts.min.js

test it and can not fix and seems break it?
![20221222173358](https://user-images.githubusercontent.com/3896160/209104197-f0833680-4977-461c-97c7-86993bce665b.png)

**Comment by fzankl** [comment]
> > @qyh214 I've uploaded a compiled and minified version to a separate branch. Just use this URL to use the version including the fix: https://raw.githubusercontent.com/fzankl/docsify-plugin-flexible-alerts/30-unable-to-display-compiled/docsify-plugin-flexible-alerts.min.js
> 
> test it and can not fix and seems break it? ![20221222173358](https://user-images.githubusercontent.com/3896160/209104197-f0833680-4977-461c-97c7-86993bce665b.png)

That's weird. I've just tested it using the compiled file and it works for me
Can you please provide the content of the respective markdown section?

**Comment by qyh214** [comment]
> > > @qyh214 I've uploaded a compiled and minified version to a separate branch. Just use this URL to use the version including the fix: https://raw.githubusercontent.com/fzankl/docsify-plugin-flexible-alerts/30-unable-to-display-compiled/docsify-plugin-flexible-alerts.min.js
> > 
> > 
> > test it and can not fix and seems break it? ![20221222173358](https://user-images.githubusercontent.com/3896160/209104197-f0833680-4977-461c-97c7-86993bce665b.png)
> 
> That's weird. I've just tested it using the compiled file and it works for me Can you please provide the content of the respective markdown section?

I think fix!I download it and use it in locale and test well.
![20221222174944](https://user-images.githubusercontent.com/3896160/209107261-2ae05b9c-3ffb-4709-be68-5438f7053ab7.png)
seems well and I have removed `space` to temporary fix.

**Comment by fzankl** [comment]
That are good news. 👍🏼 
Then I will finish the PR and make a new release.
